### ISSUE TITLE
The deploy github workflow is broken

### ISSUE THREAD

**Issue by dsebastien** [knowii-oss/knowii#973]
Tried implementing it using PRs, but the workflow is broken, it recreates the last commit with a different hash (?) and once the PR is merged, the production branch indicates "1 commit ahead, 1 commit behind main", instead of being aligned with main as it should

Fails with this:

```
name: Deploy

concurrency: production

# Manual workflow
on: workflow_dispatch

permissions:
  actions: read
  contents: write
  issues: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create and merge a PR for this deployment
      # This is a workaround for the production branch protection
      # Reference: https://github.com/krlmlr/pr-bots/blob/main/.github/workflows/write-file-branch-merge.yaml
      - run: |
          gh pr create --title "Deploy ${GITHUB_SHA}" --body "This is a Deployment PR" --repo knowii-oss/knowii --base production --head main
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          pr_number=$(gh pr list --state open --limit 1 --json number --jq '.[0].number')
          gh pr merge $pr_number --rebase
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Where we basically just
- Create a PR using `gh pr create --title "Deploy ${GITHUB_SHA}" --body "This is a Deployment PR" --repo knowii-oss/knowii --base production --head main`
- Merge that PR with a rebase: `gh pr merge $pr_number --rebase`
